### ISSUE TITLE
HA and Schlage Integration issue

### ISSUE THREAD

**Issue by mukeshwani** [mcnutter1/homeasssitant-schlage#28]
Here is the info from Logs:
2024-12-03 12:56:44.792 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration schlage which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-03 12:56:44.809 ERROR (MainThread) [homeassistant.config_entries] Config entry 'Schlage Locks' from integration schlage has an invalid unique_id '['*********']', please create a bug report at https://github.com/mcnutter1/homeasssitant-schlage/issues

**Comment by eseasholtz** [comment]
I just updated to 2024.12.1 and am getting similar error, but with more detail in my log. Also an additonal item that indicates it will stop working with the 2025.1 release in a couple of weeks:



2024-12-08 18:53:52.048 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration schlage which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2024-12-08 18:53:52.298 ERROR (MainThread) [homeassistant.config_entries] Config entry 'Schlage Locks' from integration schlage has an invalid unique_id '['*****@*********']', please create a bug report at https://github.com/mcnutter1/homeasssitant-schlage/issues

2024-12-08 18:53:57.133 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('custom_components.schlage',) in /usr/src/homeassistant/homeassistant/loader.py, line 1067: ComponentProtocol, importlib.import_module(self.pkg_path) inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
self._run_once()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
handle._run()
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component
result = await _async_setup_component(hass, domain, config)
File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
component = await integration.async_get_component()
File "/usr/src/homeassistant/homeassistant/loader.py", line 1019, in async_get_component
comp = self._get_component()
File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
ComponentProtocol, importlib.import_module(self.pkg_path)

2024-12-08 18:54:08.029 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'schlage' calls async_forward_entry_setup for integration, schlage with title: Schlage Locks and entry_id: ********************, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/schlage/__init__.py, line 92: hass.async_create_task(, please create a bug report at https://github.com/mcnutter1/homeasssitant-schlage/issues

2024-12-08 18:54:08.066 WARNING (ImportExecutor_0) [homeassistant.const] STATE_LOCKED was used from schlage, this is a deprecated constant which will be removed in HA Core 2025.10. Use LockState.LOCKED instead, please report it to the author of the 'schlage' custom integration

2024-12-08 18:54:08.072 WARNING (ImportExecutor_0) [homeassistant.const] STATE_UNLOCKED was used from schlage, this is a deprecated constant which will be removed in HA Core 2025.10. Use LockState.UNLOCKED instead, please report it to the author of the 'schlage' custom integration

2024-12-08 18:54:08.139 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration schlage with title: Schlage Locks and entry_id: ********************, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

Stack (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
self._run_once()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
handle._run()
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2223, in async_forward_entry_setup
_report_non_awaited_platform_forwards(entry, "async_forward_entry_setup")
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1192, in _report_non_awaited_platform_forwards
report(
File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 155, in report
_LOGGER.warning(msg, stack_info=True)

2024-12-08 18:54:08.151 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration schlage with title: Schlage Locks and entry_id: ********************, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

Stack (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
self._run_once()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
handle._run()
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2223, in async_forward_entry_setup
_report_non_awaited_platform_forwards(entry, "async_forward_entry_setup")
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1192, in _report_non_awaited_platform_forwards
report(
File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 155, in report
_LOGGER.warning(msg, stack_info=True)
