### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by josephny** [mcnutter1/homeasssitant-schlage#5]

**Comment by jimcj1301** [comment]
## Installation
### *Manual*
**(1)** Download the code zip file from Github

**(2)** Unzip the code and place the `custom_components` folder in your configuration directory (or add its contents to an existing `custom_components` folder).
It should look similar to this:
```
<config directory>/
|-- custom_components/
|   |-- homeasssitant-schlage/
|       |-- __init__.py
|       |-- config_flow.py
|       |-- const.py
|       |-- lock.py
|       |-- etc...
```

**(3)** Restart Home Assistant

**(4)** Install the new integration via the Home Assistant UI. "Settings --> Devices & Services --> Integrations" and then click "+ Add Integration" in the bottom right hand corner. Search for the Schlage integration.

**(5)** Enter your Schlage account information into the pop-up window.

**Comment by jimcj1301** [comment]
Integration is still not working but that is how to install it according to documents.

**Comment by mcnutter1** [comment]
Whats not working? It works OK for me as of this morning, do you have the schlage encode locks? Can you send the error?

**Comment by jimcj1301** [comment]
This is the error I'm getting. Also on the integration tile there is no icon or information. Let me know if theres any recommendations that I can change. 

Logger: homeassistant.helpers.integration_platform
Source: loader.py:739
First occurred: 9:54:22 PM (8 occurrences)
Last logged: 9:54:33 PM

Unexpected error importing schlage/system_health.py
Unexpected error importing schlage/diagnostics.py
Unexpected error importing schlage/recorder.py
Unexpected error importing schlage/significant_change.py
Unexpected error importing schlage/cast.py
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 40, in _async_process_single_integration_platform_component
    platform = integration.get_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 722, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 739, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.homeasssitant-schlage-main.group'

**Comment by AndreasBVB** [comment]
Hi Thank you for creating this component. I tried installing it but after rebooting I still cannot find the Schlage integration. My current folder structure is like this:

root@debian-hasup:~$ ls -l /usr/share/hassio/homeassistant/custom_components/homeasssitant-schlage/
total 40
-rw-r--r-- 1 root root 3237 Sep  6 11:54 __init__.py
-rw-r--r-- 1 root root 2187 Sep  6 11:54 config_flow.py
-rw-r--r-- 1 root root  197 Sep  6 11:54 const.py
-rw-r--r-- 1 root root 3176 Sep  6 11:54 lock.py
-rw-r--r-- 1 root root  360 Sep  6 11:54 manifest.json
-rw-r--r-- 1 root root 4990 Sep  6 11:54 new_api.py
-rw-r--r-- 1 root root 2620 Sep  6 11:54 sensor.py
-rw-r--r-- 1 root root  571 Sep  6 11:54 strings.json
drwxr-xr-x 2 root root 4096 Sep  6 11:54 translations
